development:
  host: localhost
  database: fastspec_development

test:
  host: localhost
  database: fastspec_test

# set these environment variables on your prod server
production:
  host: localhost
  database: fastspec_production
  #host: <%= ENV['MONGOID_HOST'] %>
  #port: <%= ENV['MONGOID_PORT'] %>
  #username: <%= ENV['MONGOID_USERNAME'] %>
  #password: <%= ENV['MONGOID_PASSWORD'] %>
  #database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
